name: Run test

on:
  pull_request:
    types: [opened, synchronize]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    # using sccache 
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target          
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: visvirial/sccache-action@v1
        with:
          cache-key: ${{ runner.os }}-sccache-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo build --verbose
      - run: cargo test --verbose
